[book]
authors = ["cncsmonster"]
language = "en"
multilingual = false
src = "src"
title = "cncsmonster-books"

# 使用toc插件
[preprocessors.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 4


